Correção da coleta do mês de fevereiro de 2022.
dadosjusbr/coletor-mppe pull request #14
Opened 2022-04-14 15:13 UTC by duardoqueiroz

2022-04-15 13:17 UTC, danielfireman requested changes

2022-04-15 13:17 UTC, danielfireman commented on README.md
> +- Adicionar arquivo **.env** na raíz do projeto, com as variáveis do arquivo **.env.example**.
Isso não deve ser obrigatório. A pessoa pode passar as variáveis de ambiente de forma ad-hoc (sem ser via arquivo .env)

2022-04-15 13:17 UTC, danielfireman commented on README.md
> +- Adicionar arquivo **.env** na raíz do projeto, com as variáveis de ambiente, e seus valores, descritas no arquivo **.env.example**;
Como eu falei, não deve ser obrigatório.

2022-04-15 13:17 UTC, danielfireman commented on README.md
> +- Rodar o comando `python src/main.py`.
Esse ponto está no lugar errado, não? Imagino que deveria ser na linha 18.

2022-04-15 13:17 UTC, danielfireman commented on src/main.py
> +load_dotenv()
Tratar erro quando o arquivo não existir.

2022-04-18 11:14 UTC, duardoqueiroz commented on src/main.py
> +load_dotenv()
Pelo o que eu vi, nenhum erro é retornado quando o arquivo não existe

2022-04-18 12:03 UTC, joaolgm approved these changes

2022-04-19 01:01 UTC, danielfireman requested changes

2022-04-19 01:01 UTC, danielfireman commented on src/main.py
> +arg_parser = argparse.ArgumentParser(description="Coletor de dados do MPPE")
os argumentos de estágio de um pipeline dadosjusbr **devem** ser variáveis de ambiente.

Qual o motivo para ter eles como argumentos e como variáveis de abiente e ficar diferente de todos os outros coletores?

2022-04-20 15:55 UTC, danielfireman approved these changes

2022-04-22 12:46 UTC, merged