Coletor MPPE: agora utilizando o novo layout
dadosjusbr/coletor-mppe pull request #8
Opened 2021-11-29 13:18 UTC by marcos-inja

## MPPE utilizando o novo layout
> Esse **PR** atualiza o coletor **MPPE**

@danielfireman

2021-11-29 14:55 UTC, danielfireman requested changes

2021-11-29 14:55 UTC, danielfireman commented on src/data.py
> +                f"./output/{self.year}_{self.month}_remu.xlsx"
Consolidar nomes dos arquivos com os que já temos em outros coletores.

Aqui e abaixo

2021-11-29 14:55 UTC, danielfireman commented on src/data.py
> +                f"./output/{self.year}_{self.month}_remu.xlsx"
Tem que criar issue dizendo da falta desse arquivo

2021-11-29 14:55 UTC, danielfireman commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.RASPAGEM_DIFICULTADA
Poderia, por favor, adicionar um comentário explicando isso?

2021-11-29 14:55 UTC, danielfireman commented on src/output_test/expected_2019.json
> +                        "tipoReceita": "O"
não devemos ter tipo receita em débitos

2021-11-29 14:55 UTC, danielfireman commented on src/test_parser.py
> +        # Json com a saida esperada
Verificar comentário

2021-11-29 17:23 UTC, danielfireman requested changes

2021-11-29 17:23 UTC, danielfireman commented on src/crawler.py
> +		file_name = year + "_" + month + "_" + key + '.xlsx'
acho que não está no padrão, certo?

2021-11-30 11:29 UTC, marcos-inja commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.RASPAGEM_DIFICULTADA
Estou em duvida se deveria ser **RASPAGEM_DIFICULTADA** ou **RASPAGEM_AMIGAVEL**:
As urls seguem um formato bem consistente até certo ponto, 
- ex: https://transparencia.mppe.mp.br/index.php/contracheque/category/504-remuneracao-de-todos-os-membros-ativos-2020?download=5849:membros-ativos-03-2020

Porém no parâmentro de download na URL, vem um pequeno código que não podemos decifrar facilmente, e que muda para cada mês.
O que vocês acham? @danielfireman, @joaolgm

2021-11-30 11:38 UTC, marcos-inja commented on src/crawler.py
> +		file_name = year + "_" + month + "_" + key + '.xlsx'
O formato que o mppe entrega é **xlsx**, atualizo o proto novamente para adicionar essa extensão?

2021-11-30 13:31 UTC, joaolgm commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.RASPAGEM_DIFICULTADA
Creio que, só por causa desse código (o fato de mudar todos os meses e não ter um padrão para essa mudança), seja **RASPAGEM_DIFICULTADA**.

2021-11-30 18:52 UTC, danielfireman-ifal commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.RASPAGEM_DIFICULTADA
Concordo. Gostei que Marcos já comentou.

2021-11-30 18:52 UTC, danielfireman-ifal approved these changes

2021-12-01 18:45 UTC, danielfireman approved these changes

2021-12-02 13:35 UTC, joaolgm approved these changes

2021-12-03 12:56 UTC, merged